apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: arturgssjr/api-consulta-bigdata:latest
          command: ["/bin/sh", "-c", "/var/www/docker/php-fpm/entrypoint.sh"]
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: app-configmap
              mountPath: /var/www/.env
              subPath: .env
            - name: code
              mountPath: /code
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: app-configmap
          configMap:
            name: app-configmap
            items:
              - key: env
                path: .env
