apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: code
              mountPath: /code
            - name: nginx-configmap
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: code
          persistentVolumeClaim:
            claimName: code
        - name: nginx-configmap
          configMap:
            name: nginx-configmap
            items:
              - key: config
                path: default.conf
